name:           vkhoi
highlighter:    rouge
markdown:       redcarpet
redcarpet:
extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:       kramdown
permalink:      /notes/:title